app:
  title: Gartner Developer Portal
  baseUrl: http://localhost:3000

organization:
  name: Gartner

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7000
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
    # Default Helmet Content-Security-Policy values can be removed by setting the key to false
  cors:
    origin: http://localhost:3000
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'          
  cache:
    store: memory
    workingDirectory: /tmp # Use this to configure a working directory for the scaffolder, defaults to the OS temp-dir

integrations:
  bitbucket:
    - host: git.gartner.com
      token: ${BITBUCKET_PROD_AUTH_TOKEN}
      username: svcbackstage
      #appPassword: ${BITBUCKET_PROD_PWD}
      apiBaseUrl: https://git.gartner.com/rest/api/1.0
    - host: gitdev.gartner.com
      token: ${BITBUCKET_NP_AUTH_TOKEN}
      username: svcbackstage
      #appPassword: ${BITBUCKET_NP_PWD}
      apiBaseUrl: https://gitdev.gartner.com/rest/api/1.0


proxy:
  '/company':
    target: https://gartner.com
    changeOrigin: true

# Reference documentation http://backstage.io/docs/features/techdocs/configuration
# Note: After experimenting with basic setup, use CI/CD to generate docs
# and an external cloud storage when deploying TechDocs for production use-case.
# https://backstage.io/docs/features/techdocs/how-to-guides#how-to-migrate-from-techdocs-basic-to-recommended-deployment-approach
techdocs:
  builder: 'local' 
  generator:
    runIn: 'local'
  publisher:
    type: 'local'

auth:
  environment: production
  providers:
    okta:
      development:
        clientId: 0oa11lxdy7ti2USUS0h8
        clientSecret: ${AUTH_OKTA_CLIENT_SECRET}
        audience: https://gartner.oktapreview.com
      production:
        clientId: 0oa11lxdy7ti2USUS0h8
        clientSecret: ${AUTH_OKTA_CLIENT_SECRET}
        audience: https://gartner.oktapreview.com

scaffolder:
  defaultAuthor:
    name: Backstage Scaffolder
    email: svcbackstage@gartner.com
  bitbucket:
    visibility: 'private'

catalog:
  rules:
    - allow: [Component, System, API, Group, User, Resource, Location]
  locations:
    - type: url
      target: https://git.gartner.com/projects/CCNI/repos/backstage-catalog-org/raw/labgartner-inc/org.yaml
    - type: url
      target: https://git.gartner.com/projects/CCNI/repos/backstage-catalog-templates/raw/all-templates.yaml
      rules:
        - allow: [Template]

costInsights:
  engineerCost: 200000
  products:
    productA:
      name: Some Cloud Product ## required
      icon: storage
    productB:
      name: Some Other Cloud Product
      icon: data

jenkins:
  instances:
    - name: default
      baseUrl: https://jenkinsdev.svc.aws.gartner.com
      username: lmasiero
      apiKey: ${JENKINS_API_AUTH}

homepage:
  clocks:
    - label: UTC
      timezone: UTC
    - label: NYC
      timezone: 'America/New_York'
    - label: STO
      timezone: 'Europe/Stockholm'
    - label: TYO
      timezone: 'Asia/Tokyo'

kubernetes:
  customResources:
    - group: 'argoproj.io'
      apiVersion: 'v1alpha1'
      plural: 'rollouts'
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - name: ${EKS_CLUSTER_01_NAME} 
          url: ${EKS_CLUSTER_01_API}
          authProvider: 'serviceAccount'
          skipTLSVerify: true
          serviceAccountToken: ${EKS_CLUSTER_01_TOKEN}



