apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-svc
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: Praveen
  lifecycle: experimental
